export const mockedSavedAlbumsData = {
  href: "https://api.spotify.com/v1/me/albums?offset=0&limit=20",
  items: [
    {
      added_at: "2019-12-06T13:36:45Z",
      album: {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
            },
            href: "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
            id: "5Z0rUIkdvlnx6JYqcC4aU0",
            name: "Can Gox",
            type: "artist",
            uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        copyrights: [
          {
            text: "2015 Sarı Ev",
            type: "C"
          },
          {
            text: "2015 Sarı Ev",
            type: "P"
          }
        ],
        external_ids: {
          upc: "8680948002544"
        },
        external_urls: {
          spotify: "https://open.spotify.com/album/3wdk9an9mQzYAKbiLJFn1D"
        },
        genres: [],
        href: "https://api.spotify.com/v1/albums/3wdk9an9mQzYAKbiLJFn1D",
        id: "3wdk9an9mQzYAKbiLJFn1D",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b273b5caeec505b03cafc67efb20",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e02b5caeec505b03cafc67efb20",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d00004851b5caeec505b03cafc67efb20",
            width: 64
          }
        ],
        label: "Sarı Ev",
        name: "Unutama Beni",
        popularity: 42,
        release_date: "2016-08-23",
        release_date_precision: "day",
        total_tracks: 1,
        tracks: {
          href:
            "https://api.spotify.com/v1/albums/3wdk9an9mQzYAKbiLJFn1D/tracks?offset=0&limit=50",
          items: [
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 241986,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/6KIjihoDbZWqIA9TfDYz4A"
              },
              href: "https://api.spotify.com/v1/tracks/6KIjihoDbZWqIA9TfDYz4A",
              id: "6KIjihoDbZWqIA9TfDYz4A",
              is_local: false,
              name: "Unutama Beni",
              preview_url:
                "https://p.scdn.co/mp3-preview/66d9b9f5fbbc58d67da4387fb7045babcc96e578?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 1,
              type: "track",
              uri: "spotify:track:6KIjihoDbZWqIA9TfDYz4A"
            }
          ],
          limit: 50,
          next: null,
          offset: 0,
          previous: null,
          total: 1
        },
        type: "album",
        uri: "spotify:album:3wdk9an9mQzYAKbiLJFn1D"
      }
    },
    {
      added_at: "2019-12-06T13:36:42Z",
      album: {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
            },
            href: "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
            id: "5Z0rUIkdvlnx6JYqcC4aU0",
            name: "Can Gox",
            type: "artist",
            uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        copyrights: [
          {
            text: "2013 Sarı Ev",
            type: "C"
          },
          {
            text: "2013 Sarı Ev",
            type: "P"
          }
        ],
        external_ids: {
          upc: "8680948006924"
        },
        external_urls: {
          spotify: "https://open.spotify.com/album/6k3Rp24B4sxEwCM4PuAR8C"
        },
        genres: [],
        href: "https://api.spotify.com/v1/albums/6k3Rp24B4sxEwCM4PuAR8C",
        id: "6k3Rp24B4sxEwCM4PuAR8C",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ab67616d0000b2732211faa4856b4584637da6ea",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ab67616d00001e022211faa4856b4584637da6ea",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ab67616d000048512211faa4856b4584637da6ea",
            width: 64
          }
        ],
        label: "Sarı Ev",
        name: "Yalnızım Ben",
        popularity: 55,
        release_date: "2013",
        release_date_precision: "year",
        total_tracks: 9,
        tracks: {
          href:
            "https://api.spotify.com/v1/albums/6k3Rp24B4sxEwCM4PuAR8C/tracks?offset=0&limit=50",
          items: [
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 221373,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/0TOf8TNVhLVXkNUBIp6hAb"
              },
              href: "https://api.spotify.com/v1/tracks/0TOf8TNVhLVXkNUBIp6hAb",
              id: "0TOf8TNVhLVXkNUBIp6hAb",
              is_local: false,
              name: "Yalnızım Ben",
              preview_url:
                "https://p.scdn.co/mp3-preview/55985ce42f7d1e4b59c0cb4ed7fa18069da31b92?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 1,
              type: "track",
              uri: "spotify:track:0TOf8TNVhLVXkNUBIp6hAb"
            },
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 235020,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/20eHdaKRiwtfw73PDPLLRO"
              },
              href: "https://api.spotify.com/v1/tracks/20eHdaKRiwtfw73PDPLLRO",
              id: "20eHdaKRiwtfw73PDPLLRO",
              is_local: false,
              name: "Sorma",
              preview_url:
                "https://p.scdn.co/mp3-preview/fd53e7c67e749df6d9b706e83e1d6d913f201d53?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 2,
              type: "track",
              uri: "spotify:track:20eHdaKRiwtfw73PDPLLRO"
            },
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 241522,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/2zS1kh2SQPK4c3EqqRQxeq"
              },
              href: "https://api.spotify.com/v1/tracks/2zS1kh2SQPK4c3EqqRQxeq",
              id: "2zS1kh2SQPK4c3EqqRQxeq",
              is_local: false,
              name: "İnanmazsın",
              preview_url:
                "https://p.scdn.co/mp3-preview/3bdbad0d914077a35226832ead0a4779c3154bd1?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 3,
              type: "track",
              uri: "spotify:track:2zS1kh2SQPK4c3EqqRQxeq"
            },
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 212520,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/2VwM9cV9pwqCxekw5YWIW3"
              },
              href: "https://api.spotify.com/v1/tracks/2VwM9cV9pwqCxekw5YWIW3",
              id: "2VwM9cV9pwqCxekw5YWIW3",
              is_local: false,
              name: "Asla Bırakma",
              preview_url:
                "https://p.scdn.co/mp3-preview/7c19ef3009182f0c7f0afcf2aa6e96cb5b8a16ce?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 4,
              type: "track",
              uri: "spotify:track:2VwM9cV9pwqCxekw5YWIW3"
            },
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 267482,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/5vEVdg0VjZ0oPiy2sfdV3n"
              },
              href: "https://api.spotify.com/v1/tracks/5vEVdg0VjZ0oPiy2sfdV3n",
              id: "5vEVdg0VjZ0oPiy2sfdV3n",
              is_local: false,
              name: "Drama Köprüsü",
              preview_url:
                "https://p.scdn.co/mp3-preview/bc5547a9ceb12084fdfb8690de4eec42f8454a7f?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 5,
              type: "track",
              uri: "spotify:track:5vEVdg0VjZ0oPiy2sfdV3n"
            },
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 212828,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/4emTpjlikUxsVeyp13pQpm"
              },
              href: "https://api.spotify.com/v1/tracks/4emTpjlikUxsVeyp13pQpm",
              id: "4emTpjlikUxsVeyp13pQpm",
              is_local: false,
              name: "Rüzgar",
              preview_url:
                "https://p.scdn.co/mp3-preview/e8760c48aa288e5c6b0faa9917a46b8a580eab10?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 6,
              type: "track",
              uri: "spotify:track:4emTpjlikUxsVeyp13pQpm"
            },
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 217431,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/0xh0YnBwrwLkFx2Z5Q9aBO"
              },
              href: "https://api.spotify.com/v1/tracks/0xh0YnBwrwLkFx2Z5Q9aBO",
              id: "0xh0YnBwrwLkFx2Z5Q9aBO",
              is_local: false,
              name: "Dal Goncayı Bir Sabah",
              preview_url:
                "https://p.scdn.co/mp3-preview/41663f07d58835c662ba292708d04502eeb0d51a?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 7,
              type: "track",
              uri: "spotify:track:0xh0YnBwrwLkFx2Z5Q9aBO"
            },
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 225361,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/0mhXhJCqpGvYQgZGJYMIOQ"
              },
              href: "https://api.spotify.com/v1/tracks/0mhXhJCqpGvYQgZGJYMIOQ",
              id: "0mhXhJCqpGvYQgZGJYMIOQ",
              is_local: false,
              name: "Gölge",
              preview_url:
                "https://p.scdn.co/mp3-preview/012f973fc2c79a3347b84a98fa6295b6d5f4e48f?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 8,
              type: "track",
              uri: "spotify:track:0mhXhJCqpGvYQgZGJYMIOQ"
            },
            {
              artists: [
                {
                  external_urls: {
                    spotify:
                      "https://open.spotify.com/artist/5Z0rUIkdvlnx6JYqcC4aU0"
                  },
                  href:
                    "https://api.spotify.com/v1/artists/5Z0rUIkdvlnx6JYqcC4aU0",
                  id: "5Z0rUIkdvlnx6JYqcC4aU0",
                  name: "Can Gox",
                  type: "artist",
                  uri: "spotify:artist:5Z0rUIkdvlnx6JYqcC4aU0"
                }
              ],
              available_markets: [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
              ],
              disc_number: 1,
              duration_ms: 202129,
              explicit: false,
              external_urls: {
                spotify: "https://open.spotify.com/track/1sFNOpYhNimn5dPhyckf0W"
              },
              href: "https://api.spotify.com/v1/tracks/1sFNOpYhNimn5dPhyckf0W",
              id: "1sFNOpYhNimn5dPhyckf0W",
              is_local: false,
              name: "Haydar Haydar",
              preview_url:
                "https://p.scdn.co/mp3-preview/ba7ee29531a99c9a86716502cd55c8329e38cdfa?cid=5bcff691b8a04bac809e087d8a0ce7f9",
              track_number: 9,
              type: "track",
              uri: "spotify:track:1sFNOpYhNimn5dPhyckf0W"
            }
          ],
          limit: 50,
          next: null,
          offset: 0,
          previous: null,
          total: 9
        },
        type: "album",
        uri: "spotify:album:6k3Rp24B4sxEwCM4PuAR8C"
      }
    }
  ],
  limit: 20,
  next: null,
  offset: 0,
  previous: null,
  total: 2
};
