export const mockedAlbumData = {
  album_type: "album",
  artists: [
    {
      external_urls: {
        spotify: "https://open.spotify.com/artist/7su1fG75ZwXHA6ei9Zcy7T"
      },
      href: "https://api.spotify.com/v1/artists/7su1fG75ZwXHA6ei9Zcy7T",
      id: "7su1fG75ZwXHA6ei9Zcy7T",
      name: "Stavroz",
      type: "artist",
      uri: "spotify:artist:7su1fG75ZwXHA6ei9Zcy7T"
    }
  ],
  available_markets: [
    "AD",
    "AE",
    "AR",
    "AT",
    "AU",
    "BE",
    "BG",
    "BH",
    "BO",
    "BR",
    "CA",
    "CH",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DE",
    "DK",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FR",
    "GB",
    "GR",
    "GT",
    "HK",
    "HN",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JO",
    "JP",
    "KW",
    "LB",
    "LI",
    "LT",
    "LU",
    "LV",
    "MA",
    "MC",
    "MT",
    "MX",
    "MY",
    "NI",
    "NL",
    "NO",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PH",
    "PL",
    "PS",
    "PT",
    "PY",
    "QA",
    "RO",
    "SA",
    "SE",
    "SG",
    "SK",
    "SV",
    "TH",
    "TN",
    "TR",
    "TW",
    "US",
    "UY",
    "VN",
    "ZA"
  ],
  copyrights: [
    {
      text: "Délicieuse Records",
      type: "C"
    },
    {
      text: "Délicieuse Records",
      type: "P"
    }
  ],
  external_ids: {
    upc: "0848422087861"
  },
  external_urls: {
    spotify: "https://open.spotify.com/album/0cGZbzIbVOXPRr3eBA9ZLJ"
  },
  genres: [],
  href: "https://api.spotify.com/v1/albums/0cGZbzIbVOXPRr3eBA9ZLJ",
  id: "0cGZbzIbVOXPRr3eBA9ZLJ",
  images: [
    {
      height: 640,
      url: "https://i.scdn.co/image/ab67616d0000b273a3172d3d600d4c70936852fa",
      width: 640
    },
    {
      height: 300,
      url: "https://i.scdn.co/image/ab67616d00001e02a3172d3d600d4c70936852fa",
      width: 300
    },
    {
      height: 64,
      url: "https://i.scdn.co/image/ab67616d00004851a3172d3d600d4c70936852fa",
      width: 64
    }
  ],
  label: "Delicieuse Records",
  name: "The Ginning",
  popularity: 55,
  release_date: "2015-09-28",
  release_date_precision: "day",
  total_tracks: 6,
  tracks: {
    href:
      "https://api.spotify.com/v1/albums/0cGZbzIbVOXPRr3eBA9ZLJ/tracks?offset=0&limit=50",
    items: [
      {
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7su1fG75ZwXHA6ei9Zcy7T"
            },
            href: "https://api.spotify.com/v1/artists/7su1fG75ZwXHA6ei9Zcy7T",
            id: "7su1fG75ZwXHA6ei9Zcy7T",
            name: "Stavroz",
            type: "artist",
            uri: "spotify:artist:7su1fG75ZwXHA6ei9Zcy7T"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 391993,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/track/0hNlr56UPvigGSyCVdAOMi"
        },
        href: "https://api.spotify.com/v1/tracks/0hNlr56UPvigGSyCVdAOMi",
        id: "0hNlr56UPvigGSyCVdAOMi",
        is_local: false,
        name: "The Ginning",
        preview_url:
          "https://p.scdn.co/mp3-preview/90323cbc5e05a5daf5296bd97a2e7eefdbfa71e5?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track_number: 1,
        type: "track",
        uri: "spotify:track:0hNlr56UPvigGSyCVdAOMi"
      },
      {
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7su1fG75ZwXHA6ei9Zcy7T"
            },
            href: "https://api.spotify.com/v1/artists/7su1fG75ZwXHA6ei9Zcy7T",
            id: "7su1fG75ZwXHA6ei9Zcy7T",
            name: "Stavroz",
            type: "artist",
            uri: "spotify:artist:7su1fG75ZwXHA6ei9Zcy7T"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 482983,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/track/2SCLswvRP8hAYdIKsrLV6h"
        },
        href: "https://api.spotify.com/v1/tracks/2SCLswvRP8hAYdIKsrLV6h",
        id: "2SCLswvRP8hAYdIKsrLV6h",
        is_local: false,
        name: "The Finishing",
        preview_url:
          "https://p.scdn.co/mp3-preview/87de136f95054abf2471ffc9ca589a9c23906208?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track_number: 2,
        type: "track",
        uri: "spotify:track:2SCLswvRP8hAYdIKsrLV6h"
      },
      {
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7su1fG75ZwXHA6ei9Zcy7T"
            },
            href: "https://api.spotify.com/v1/artists/7su1fG75ZwXHA6ei9Zcy7T",
            id: "7su1fG75ZwXHA6ei9Zcy7T",
            name: "Stavroz",
            type: "artist",
            uri: "spotify:artist:7su1fG75ZwXHA6ei9Zcy7T"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 414434,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/track/3Od7bbbf4UVfULElSpKELt"
        },
        href: "https://api.spotify.com/v1/tracks/3Od7bbbf4UVfULElSpKELt",
        id: "3Od7bbbf4UVfULElSpKELt",
        is_local: false,
        name: "The Ginning - Felkon Remix",
        preview_url:
          "https://p.scdn.co/mp3-preview/02cd0dcf453298837334a1926e8e9ae7cf8ae5c1?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track_number: 3,
        type: "track",
        uri: "spotify:track:3Od7bbbf4UVfULElSpKELt"
      },
      {
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7su1fG75ZwXHA6ei9Zcy7T"
            },
            href: "https://api.spotify.com/v1/artists/7su1fG75ZwXHA6ei9Zcy7T",
            id: "7su1fG75ZwXHA6ei9Zcy7T",
            name: "Stavroz",
            type: "artist",
            uri: "spotify:artist:7su1fG75ZwXHA6ei9Zcy7T"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 425498,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/track/1Y3GcRwfhJa3wMdLFpGXts"
        },
        href: "https://api.spotify.com/v1/tracks/1Y3GcRwfhJa3wMdLFpGXts",
        id: "1Y3GcRwfhJa3wMdLFpGXts",
        is_local: false,
        name: "The Ginning - Britta Arnold Remix",
        preview_url:
          "https://p.scdn.co/mp3-preview/7bcf3bde241a42e90224c122922656a2e1bfaf73?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track_number: 4,
        type: "track",
        uri: "spotify:track:1Y3GcRwfhJa3wMdLFpGXts"
      },
      {
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7su1fG75ZwXHA6ei9Zcy7T"
            },
            href: "https://api.spotify.com/v1/artists/7su1fG75ZwXHA6ei9Zcy7T",
            id: "7su1fG75ZwXHA6ei9Zcy7T",
            name: "Stavroz",
            type: "artist",
            uri: "spotify:artist:7su1fG75ZwXHA6ei9Zcy7T"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 471505,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/track/4RF1IxOUatf7TU5LYOjMLg"
        },
        href: "https://api.spotify.com/v1/tracks/4RF1IxOUatf7TU5LYOjMLg",
        id: "4RF1IxOUatf7TU5LYOjMLg",
        is_local: false,
        name: "The Finishing - Powel Remix",
        preview_url:
          "https://p.scdn.co/mp3-preview/26dfa803390ac3f76b33ba6faf5f475dfec6fa83?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track_number: 5,
        type: "track",
        uri: "spotify:track:4RF1IxOUatf7TU5LYOjMLg"
      },
      {
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7su1fG75ZwXHA6ei9Zcy7T"
            },
            href: "https://api.spotify.com/v1/artists/7su1fG75ZwXHA6ei9Zcy7T",
            id: "7su1fG75ZwXHA6ei9Zcy7T",
            name: "Stavroz",
            type: "artist",
            uri: "spotify:artist:7su1fG75ZwXHA6ei9Zcy7T"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 368459,
        explicit: false,
        external_urls: {
          spotify: "https://open.spotify.com/track/70G0rxN6t88G7GvsyJYePg"
        },
        href: "https://api.spotify.com/v1/tracks/70G0rxN6t88G7GvsyJYePg",
        id: "70G0rxN6t88G7GvsyJYePg",
        is_local: false,
        name: "The Finishing - Viken Arman Remix",
        preview_url:
          "https://p.scdn.co/mp3-preview/a73b4863f7e5682d19eddf3a765b69b145aff375?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track_number: 6,
        type: "track",
        uri: "spotify:track:70G0rxN6t88G7GvsyJYePg"
      }
    ],
    limit: 50,
    next: null,
    offset: 0,
    previous: null,
    total: 6
  },
  type: "album",
  uri: "spotify:album:0cGZbzIbVOXPRr3eBA9ZLJ"
};
