export const mockedNewReleasesData = {
  albums: {
    href: "https://api.spotify.com/v1/browse/new-releases?offset=0&limit=20",
    items: [
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3dRfiJ2650SZu6GbydcHNb"
            },
            href: "https://api.spotify.com/v1/artists/3dRfiJ2650SZu6GbydcHNb",
            id: "3dRfiJ2650SZu6GbydcHNb",
            name: "John Williams",
            type: "artist",
            uri: "spotify:artist:3dRfiJ2650SZu6GbydcHNb"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/26pelVOow8ODvBktJbDiua"
        },
        href: "https://api.spotify.com/v1/albums/26pelVOow8ODvBktJbDiua",
        id: "26pelVOow8ODvBktJbDiua",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/6022c8750e889021267e262aac08c43a44b79d54",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/cb9c59d663ef9f81103bb0e87407fa9b168290b5",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/4cb923e17527cffe600dec554307ed360efa5f9c",
            width: 64
          }
        ],
        name:
          "Star Wars: The Rise of Skywalker (Original Motion Picture Soundtrack)",
        release_date: "2019-12-18",
        release_date_precision: "day",
        total_tracks: 19,
        type: "album",
        uri: "spotify:album:26pelVOow8ODvBktJbDiua"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4aP1lp10BRYZO658B2NwkG"
            },
            href: "https://api.spotify.com/v1/artists/4aP1lp10BRYZO658B2NwkG",
            id: "4aP1lp10BRYZO658B2NwkG",
            name: "Andrew Lloyd Webber",
            type: "artist",
            uri: "spotify:artist:4aP1lp10BRYZO658B2NwkG"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/14NWgL804kf79W2dJuGxRl"
            },
            href: "https://api.spotify.com/v1/artists/14NWgL804kf79W2dJuGxRl",
            id: "14NWgL804kf79W2dJuGxRl",
            name: 'Cast Of The Motion Picture "Cats"',
            type: "artist",
            uri: "spotify:artist:14NWgL804kf79W2dJuGxRl"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3OjtXmDVcfHAjJOS3xBoYU"
        },
        href: "https://api.spotify.com/v1/albums/3OjtXmDVcfHAjJOS3xBoYU",
        id: "3OjtXmDVcfHAjJOS3xBoYU",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/99cd035e1f3fdb4ad5ee879cf376a4ce136144c0",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/626d90a5aae28553d97a4915507d58ed67e07ecb",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/628931caf56b51b30a76aa6bac0eb62c2bc3042e",
            width: 64
          }
        ],
        name: "Cats: Highlights From The Motion Picture Soundtrack",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 16,
        type: "album",
        uri: "spotify:album:3OjtXmDVcfHAjJOS3xBoYU"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/50co4Is1HCEo8bhOyUWKpn"
            },
            href: "https://api.spotify.com/v1/artists/50co4Is1HCEo8bhOyUWKpn",
            id: "50co4Is1HCEo8bhOyUWKpn",
            name: "Young Thug",
            type: "artist",
            uri: "spotify:artist:50co4Is1HCEo8bhOyUWKpn"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/24jAbLMFzCTlIv3kQ94HwK"
        },
        href: "https://api.spotify.com/v1/albums/24jAbLMFzCTlIv3kQ94HwK",
        id: "24jAbLMFzCTlIv3kQ94HwK",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/52e0d0675e99a0311afc156dca21e0491172dd01",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ed3d6019abb7e642a3fd02097daa0c9e75477ffa",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/a455771712d1cc715612960d0c29f3b625163eda",
            width: 64
          }
        ],
        name: "So Much Fun (Deluxe)",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 24,
        type: "album",
        uri: "spotify:album:24jAbLMFzCTlIv3kQ94HwK"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0ErzCpIMyLcjPiwT4elrtZ"
            },
            href: "https://api.spotify.com/v1/artists/0ErzCpIMyLcjPiwT4elrtZ",
            id: "0ErzCpIMyLcjPiwT4elrtZ",
            name: "NLE Choppa",
            type: "artist",
            uri: "spotify:artist:0ErzCpIMyLcjPiwT4elrtZ"
          }
        ],
        available_markets: [
          "AE",
          "AU",
          "BG",
          "BH",
          "CY",
          "EE",
          "EG",
          "FI",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LV",
          "MY",
          "NZ",
          "OM",
          "PH",
          "PS",
          "QA",
          "RO",
          "SA",
          "SG",
          "TH",
          "TR",
          "TW",
          "VN",
          "ZA",
          "AD",
          "AT",
          "BE",
          "CH",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "MT",
          "NL",
          "NO",
          "PL",
          "SE",
          "SK",
          "TN",
          "GB",
          "IE",
          "IS",
          "PT",
          "AR",
          "BR",
          "CL",
          "PY",
          "UY",
          "BO",
          "DO",
          "CA",
          "CO",
          "EC",
          "PA",
          "PE",
          "US",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3NfNZB1fjbfFm3vMdCrc0b"
        },
        href: "https://api.spotify.com/v1/albums/3NfNZB1fjbfFm3vMdCrc0b",
        id: "3NfNZB1fjbfFm3vMdCrc0b",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/cc99dba155ad6a8cf1d466401df0c3c11418de66",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/3ce9c776af765356764fcd08d6f21761fac293d6",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/2dcb845af8098e5033a9e31a6ca38086efbe47a1",
            width: 64
          }
        ],
        name: "Cottonwood",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 9,
        type: "album",
        uri: "spotify:album:3NfNZB1fjbfFm3vMdCrc0b"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
            },
            href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
            id: "0LyfQWJT6nXafLPZqxe9Of",
            name: "Çeşitli Sanatçılar",
            type: "artist",
            uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
          }
        ],
        available_markets: [
          "AE",
          "AU",
          "BG",
          "BH",
          "CY",
          "EE",
          "EG",
          "FI",
          "GR",
          "HK",
          "ID",
          "IL",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LV",
          "MY",
          "NZ",
          "OM",
          "PH",
          "PS",
          "QA",
          "RO",
          "SA",
          "SG",
          "TH",
          "TR",
          "TW",
          "VN",
          "ZA",
          "AD",
          "AT",
          "BE",
          "CH",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "MT",
          "NL",
          "NO",
          "PL",
          "SE",
          "SK",
          "TN",
          "GB",
          "IE",
          "IS",
          "PT",
          "AR",
          "BR",
          "CL",
          "PY",
          "UY",
          "BO",
          "DO",
          "CA",
          "CO",
          "EC",
          "PA",
          "PE",
          "US",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1sKGQZB3ZQeQ7TE02D3mSm"
        },
        href: "https://api.spotify.com/v1/albums/1sKGQZB3ZQeQ7TE02D3mSm",
        id: "1sKGQZB3ZQeQ7TE02D3mSm",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/38bed685bc27218683d52f28443d3de999ef7518",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/81a48e30aba1fc8b72d992f15f1d0fb78be9e451",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/1408d0a11577bce4ff91b0d16dd9ca21ee2a0fb1",
            width: 64
          }
        ],
        name: "For Real",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:1sKGQZB3ZQeQ7TE02D3mSm"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/13y7CgLHjMVRMDqxdx0Xdo"
            },
            href: "https://api.spotify.com/v1/artists/13y7CgLHjMVRMDqxdx0Xdo",
            id: "13y7CgLHjMVRMDqxdx0Xdo",
            name: "Gucci Mane",
            type: "artist",
            uri: "spotify:artist:13y7CgLHjMVRMDqxdx0Xdo"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/41Mzki3Yox73btDc51evLi"
        },
        href: "https://api.spotify.com/v1/albums/41Mzki3Yox73btDc51evLi",
        id: "41Mzki3Yox73btDc51evLi",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ceb83551ee9a530ca0344aa40af48a405d263bd1",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/d4ca1ada2083244e594f65eb5f383a4d0fee76e2",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/9c04ac8b6392e10902a3a9474723f5a02decef50",
            width: 64
          }
        ],
        name: "East Atlanta Santa 3",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 16,
        type: "album",
        uri: "spotify:album:41Mzki3Yox73btDc51evLi"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4SsVbpTthjScTS7U2hmr1X"
            },
            href: "https://api.spotify.com/v1/artists/4SsVbpTthjScTS7U2hmr1X",
            id: "4SsVbpTthjScTS7U2hmr1X",
            name: "Arcangel",
            type: "artist",
            uri: "spotify:artist:4SsVbpTthjScTS7U2hmr1X"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0CPLMVp7rMi3BkzAMve96K"
        },
        href: "https://api.spotify.com/v1/albums/0CPLMVp7rMi3BkzAMve96K",
        id: "0CPLMVp7rMi3BkzAMve96K",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/2603cc5bad6175fc4c5418f3f6000571d817115e",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/e2b9297466a8178e1683495f7ca711e673d45dfe",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/e5bd8b2563984faccf82381cabea23a02630d4bc",
            width: 64
          }
        ],
        name: "Historias de un Capricornio",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 15,
        type: "album",
        uri: "spotify:album:0CPLMVp7rMi3BkzAMve96K"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4Ga1P7PMIsmqEZqhYZQgDo"
            },
            href: "https://api.spotify.com/v1/artists/4Ga1P7PMIsmqEZqhYZQgDo",
            id: "4Ga1P7PMIsmqEZqhYZQgDo",
            name: "Lil Tecca",
            type: "artist",
            uri: "spotify:artist:4Ga1P7PMIsmqEZqhYZQgDo"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6t3XY3pufq7luAGEopwu6h"
        },
        href: "https://api.spotify.com/v1/albums/6t3XY3pufq7luAGEopwu6h",
        id: "6t3XY3pufq7luAGEopwu6h",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/92e6facccaa5dd3168e39728688b25c872f3723d",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/f9eabecb883ff46fbe4447747c1580bc174e54dd",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/841306366fa4d5a2e7b9d5692d34c3f6b3fbba53",
            width: 64
          }
        ],
        name: "why u look mad",
        release_date: "2019-12-16",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:6t3XY3pufq7luAGEopwu6h"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2kqUKsTuEj1lPbm6BSn1AU"
            },
            href: "https://api.spotify.com/v1/artists/2kqUKsTuEj1lPbm6BSn1AU",
            id: "2kqUKsTuEj1lPbm6BSn1AU",
            name: "Rich Music LTD",
            type: "artist",
            uri: "spotify:artist:2kqUKsTuEj1lPbm6BSn1AU"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/77ziqFxp5gaInVrF2lj4ht"
            },
            href: "https://api.spotify.com/v1/artists/77ziqFxp5gaInVrF2lj4ht",
            id: "77ziqFxp5gaInVrF2lj4ht",
            name: "Sech",
            type: "artist",
            uri: "spotify:artist:77ziqFxp5gaInVrF2lj4ht"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0KPX4Ucy9dk82uj4GpKesn"
            },
            href: "https://api.spotify.com/v1/artists/0KPX4Ucy9dk82uj4GpKesn",
            id: "0KPX4Ucy9dk82uj4GpKesn",
            name: "Dalex",
            type: "artist",
            uri: "spotify:artist:0KPX4Ucy9dk82uj4GpKesn"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6jU5obP9snCcR57UjL9byA"
        },
        href: "https://api.spotify.com/v1/albums/6jU5obP9snCcR57UjL9byA",
        id: "6jU5obP9snCcR57UjL9byA",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/dabcf0736c48e1068719f61e85d64d001dcf10d5",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/f3d3ab1a5dabf7c90cf74f2cb67d9c4dc877ad06",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/763499c08bdba9b38877590100ba773c593da285",
            width: 64
          }
        ],
        name: "Rich Music Sessions (Acústico En Vivo)",
        release_date: "2019-12-18",
        release_date_precision: "day",
        total_tracks: 8,
        type: "album",
        uri: "spotify:album:6jU5obP9snCcR57UjL9byA"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5Vuvs6Py2JRU7WiFDVsI7J"
            },
            href: "https://api.spotify.com/v1/artists/5Vuvs6Py2JRU7WiFDVsI7J",
            id: "5Vuvs6Py2JRU7WiFDVsI7J",
            name: "Lucky Daye",
            type: "artist",
            uri: "spotify:artist:5Vuvs6Py2JRU7WiFDVsI7J"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0iRhoLbrny7qdvxdclPcaO"
        },
        href: "https://api.spotify.com/v1/albums/0iRhoLbrny7qdvxdclPcaO",
        id: "0iRhoLbrny7qdvxdclPcaO",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/bb756e1bfef92a5346010f866aad0e618624f109",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/6d46e614324834eb9142b255dda9df0c120802a8",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/8422489e3295608c3bcf38a87992aca0f4713dfc",
            width: 64
          }
        ],
        name: "Roll Some Mo (feat. Ty Dolla $ign & Wale) [Remix]",
        release_date: "2019-12-18",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:0iRhoLbrny7qdvxdclPcaO"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6TIYQ3jFPwQSRmorSezPxX"
            },
            href: "https://api.spotify.com/v1/artists/6TIYQ3jFPwQSRmorSezPxX",
            id: "6TIYQ3jFPwQSRmorSezPxX",
            name: "Machine Gun Kelly",
            type: "artist",
            uri: "spotify:artist:6TIYQ3jFPwQSRmorSezPxX"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0Cdk8wZXVrYX2ZyCwjTEjs"
        },
        href: "https://api.spotify.com/v1/albums/0Cdk8wZXVrYX2ZyCwjTEjs",
        id: "0Cdk8wZXVrYX2ZyCwjTEjs",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ae72adac43c32148b4ce9e8f3746526aa2a86cb6",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/3c174f6e9dba13f7c44de98a831226fe03eba582",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/9f3b228c66f96417493d762aa2f7be36cc99e964",
            width: 64
          }
        ],
        name: "why are you here",
        release_date: "2019-12-18",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:0Cdk8wZXVrYX2ZyCwjTEjs"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/62DmErcU7dqZbJaDqwsqzR"
            },
            href: "https://api.spotify.com/v1/artists/62DmErcU7dqZbJaDqwsqzR",
            id: "62DmErcU7dqZbJaDqwsqzR",
            name: "Popcaan",
            type: "artist",
            uri: "spotify:artist:62DmErcU7dqZbJaDqwsqzR"
          }
        ],
        available_markets: [
          "AE",
          "AU",
          "BG",
          "BH",
          "CY",
          "EE",
          "EG",
          "FI",
          "GR",
          "HK",
          "ID",
          "IL",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LV",
          "MY",
          "NZ",
          "OM",
          "PH",
          "PS",
          "QA",
          "RO",
          "SA",
          "SG",
          "TH",
          "TR",
          "TW",
          "VN",
          "ZA",
          "AD",
          "AT",
          "BE",
          "CH",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "MT",
          "NL",
          "NO",
          "PL",
          "SE",
          "SK",
          "TN",
          "GB",
          "IE",
          "IS",
          "PT",
          "AR",
          "BR",
          "CL",
          "PY",
          "UY",
          "BO",
          "DO",
          "CA",
          "CO",
          "EC",
          "PA",
          "PE",
          "US",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6h9zRriP6rftIyWyqzrJRp"
        },
        href: "https://api.spotify.com/v1/albums/6h9zRriP6rftIyWyqzrJRp",
        id: "6h9zRriP6rftIyWyqzrJRp",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/92719b21a99e8c2654e09355cdb25ad9ac52f6cb",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/e6cea78214ed0d3ea3c1cc4bcf7b5560dae1c97c",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/2e8c4c6709c809ec3fb09843252b1146a443478a",
            width: 64
          }
        ],
        name: "Vanquish",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 10,
        type: "album",
        uri: "spotify:album:6h9zRriP6rftIyWyqzrJRp"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG"
            },
            href: "https://api.spotify.com/v1/artists/1McMsnEElThX1knmY4oliG",
            id: "1McMsnEElThX1knmY4oliG",
            name: "Olivia Rodrigo",
            type: "artist",
            uri: "spotify:artist:1McMsnEElThX1knmY4oliG"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/3dmltV5S6vUXzQD4DmpwFq"
        },
        href: "https://api.spotify.com/v1/albums/3dmltV5S6vUXzQD4DmpwFq",
        id: "3dmltV5S6vUXzQD4DmpwFq",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/08464a84f625d0cd97a258939279bb3ba181015e",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/5cbc0cc1ee99616f8f2bc8429ab1c0c912b25e7e",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/1cf3463f70b122bd13b89a9d216ef1bad5f19af7",
            width: 64
          }
        ],
        name:
          'Out of the Old (From "High School Musical: The Musical: The Series")',
        release_date: "2019-12-18",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:3dmltV5S6vUXzQD4DmpwFq"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0XIKGBo9PnK1ApI5tZA60d"
            },
            href: "https://api.spotify.com/v1/artists/0XIKGBo9PnK1ApI5tZA60d",
            id: "0XIKGBo9PnK1ApI5tZA60d",
            name: "DaniLeigh",
            type: "artist",
            uri: "spotify:artist:0XIKGBo9PnK1ApI5tZA60d"
          }
        ],
        available_markets: [
          "AE",
          "AU",
          "BG",
          "BH",
          "CY",
          "EE",
          "EG",
          "FI",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LV",
          "MY",
          "NZ",
          "OM",
          "PH",
          "PS",
          "QA",
          "RO",
          "SA",
          "SG",
          "TH",
          "TR",
          "TW",
          "VN",
          "ZA",
          "AD",
          "AT",
          "BE",
          "CH",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "MT",
          "NL",
          "NO",
          "PL",
          "SE",
          "SK",
          "TN",
          "GB",
          "IE",
          "IS",
          "PT",
          "AR",
          "BR",
          "CL",
          "PY",
          "UY",
          "BO",
          "DO",
          "CA",
          "CO",
          "EC",
          "PA",
          "PE",
          "US",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6HBkgqVYDCoz430BEtkNWd"
        },
        href: "https://api.spotify.com/v1/albums/6HBkgqVYDCoz430BEtkNWd",
        id: "6HBkgqVYDCoz430BEtkNWd",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/ea5aa3e6d1708ede47860d1d7e09f7c0ac0d872b",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/88d5b53b0520d7ab88580af5983e580fde2aab37",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/c268621822c114d1c26cc85af9d945ebacae6c3d",
            width: 64
          }
        ],
        name: "My Present",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 4,
        type: "album",
        uri: "spotify:album:6HBkgqVYDCoz430BEtkNWd"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5ictveRyhWRs8Gt8Dvt1hS"
            },
            href: "https://api.spotify.com/v1/artists/5ictveRyhWRs8Gt8Dvt1hS",
            id: "5ictveRyhWRs8Gt8Dvt1hS",
            name: "The Front Bottoms",
            type: "artist",
            uri: "spotify:artist:5ictveRyhWRs8Gt8Dvt1hS"
          }
        ],
        available_markets: [
          "AE",
          "AU",
          "BG",
          "BH",
          "CY",
          "EE",
          "EG",
          "FI",
          "GR",
          "HK",
          "ID",
          "IL",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LV",
          "MY",
          "NZ",
          "OM",
          "PH",
          "PS",
          "QA",
          "RO",
          "SA",
          "SG",
          "TH",
          "TR",
          "TW",
          "VN",
          "ZA",
          "AD",
          "AT",
          "BE",
          "CH",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "MT",
          "NL",
          "NO",
          "PL",
          "SE",
          "SK",
          "TN",
          "GB",
          "IE",
          "IS",
          "PT",
          "AR",
          "BR",
          "CL",
          "PY",
          "UY",
          "BO",
          "DO",
          "CA",
          "CO",
          "EC",
          "PA",
          "PE",
          "US",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/0KZsf82vQ6Yo59fgVjsF3Q"
        },
        href: "https://api.spotify.com/v1/albums/0KZsf82vQ6Yo59fgVjsF3Q",
        id: "0KZsf82vQ6Yo59fgVjsF3Q",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/50cf8161b9470a3a4c77a43b67dca7fe07b6a7c2",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/411fc07064126d92b0f0ac143ab8ff82d839fd38",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/053112002f72b060e3f4a8f80eb9956c081a636f",
            width: 64
          }
        ],
        name: "Camouflage",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:0KZsf82vQ6Yo59fgVjsF3Q"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6aLoJJxz7MV2iZ423S8tJC"
            },
            href: "https://api.spotify.com/v1/artists/6aLoJJxz7MV2iZ423S8tJC",
            id: "6aLoJJxz7MV2iZ423S8tJC",
            name: "Doe Boy",
            type: "artist",
            uri: "spotify:artist:6aLoJJxz7MV2iZ423S8tJC"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/6nmbe1qYXmSflr1COvPIrN"
        },
        href: "https://api.spotify.com/v1/albums/6nmbe1qYXmSflr1COvPIrN",
        id: "6nmbe1qYXmSflr1COvPIrN",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/6f4249b3f40db6ffc825b1d2bc75985a58634212",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/a8bba8c23fb01868d82f9eb1be723313925fc65a",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/88fe6ddd772a1338f6d29891db9c8dfde2b0b1fe",
            width: 64
          }
        ],
        name: "Streetz Need Me 2",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 15,
        type: "album",
        uri: "spotify:album:6nmbe1qYXmSflr1COvPIrN"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7t7KCNFOwuMChaQg6L8I69"
            },
            href: "https://api.spotify.com/v1/artists/7t7KCNFOwuMChaQg6L8I69",
            id: "7t7KCNFOwuMChaQg6L8I69",
            name: "Jacob Latimore",
            type: "artist",
            uri: "spotify:artist:7t7KCNFOwuMChaQg6L8I69"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1QSe34NLmqc0MiZ3DeEVsA"
        },
        href: "https://api.spotify.com/v1/albums/1QSe34NLmqc0MiZ3DeEVsA",
        id: "1QSe34NLmqc0MiZ3DeEVsA",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/1802b88fbc8ad248c4d25f12250af737af346024",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/b653505f45fa1d0d8694f43b5fb1eae55b073bed",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/bbd5eb54cddf634fb425fbf1c5da716d078c3068",
            width: 64
          }
        ],
        name: "Don't Wanna Leave",
        release_date: "2019-12-18",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:1QSe34NLmqc0MiZ3DeEVsA"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/6KZDXtSj0SzGOV705nNeh3"
            },
            href: "https://api.spotify.com/v1/artists/6KZDXtSj0SzGOV705nNeh3",
            id: "6KZDXtSj0SzGOV705nNeh3",
            name: "Kid Ink",
            type: "artist",
            uri: "spotify:artist:6KZDXtSj0SzGOV705nNeh3"
          }
        ],
        available_markets: [
          "AE",
          "AU",
          "BG",
          "BH",
          "CY",
          "EE",
          "EG",
          "FI",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LV",
          "MY",
          "NZ",
          "OM",
          "PH",
          "PS",
          "QA",
          "RO",
          "SA",
          "SG",
          "TH",
          "TR",
          "TW",
          "VN",
          "ZA",
          "AD",
          "AT",
          "BE",
          "CH",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "MT",
          "NL",
          "NO",
          "PL",
          "SE",
          "SK",
          "TN",
          "GB",
          "IE",
          "IS",
          "PT",
          "AR",
          "BR",
          "CL",
          "PY",
          "UY",
          "BO",
          "DO",
          "CA",
          "CO",
          "EC",
          "PA",
          "PE",
          "US",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1FgiHGd13V75YJnGFGPIIB"
        },
        href: "https://api.spotify.com/v1/albums/1FgiHGd13V75YJnGFGPIIB",
        id: "1FgiHGd13V75YJnGFGPIIB",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/0edbdeb6f85bfc6998c20b5c1bb85b9ef2648199",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/ed4ca9d99c5ec841e513b79e4ae6f5f46b6d199e",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/14a209860fb3c96c0e506137030a5b6957a84648",
            width: 64
          }
        ],
        name: "FCUKIZYOUDOIN",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 1,
        type: "album",
        uri: "spotify:album:1FgiHGd13V75YJnGFGPIIB"
      },
      {
        album_type: "single",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5xuNBZoM7z1Vv8IQ6uM0p6"
            },
            href: "https://api.spotify.com/v1/artists/5xuNBZoM7z1Vv8IQ6uM0p6",
            id: "5xuNBZoM7z1Vv8IQ6uM0p6",
            name: "JoJo",
            type: "artist",
            uri: "spotify:artist:5xuNBZoM7z1Vv8IQ6uM0p6"
          }
        ],
        available_markets: [
          "AE",
          "AU",
          "BG",
          "BH",
          "CY",
          "EE",
          "EG",
          "FI",
          "GR",
          "HK",
          "ID",
          "IL",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LV",
          "MY",
          "NZ",
          "OM",
          "PH",
          "PS",
          "QA",
          "RO",
          "SA",
          "SG",
          "TH",
          "TR",
          "TW",
          "VN",
          "ZA",
          "AD",
          "AT",
          "BE",
          "CH",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "MT",
          "NL",
          "NO",
          "PL",
          "SE",
          "SK",
          "TN",
          "GB",
          "IE",
          "IS",
          "PT",
          "AR",
          "BR",
          "CL",
          "PY",
          "UY",
          "BO",
          "DO",
          "CA",
          "CO",
          "EC",
          "PA",
          "PE",
          "US",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/48ZwTu08oO1in9tgSh6aGY"
        },
        href: "https://api.spotify.com/v1/albums/48ZwTu08oO1in9tgSh6aGY",
        id: "48ZwTu08oO1in9tgSh6aGY",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/5121f5b6c5e815f07529cfedadaefebd93acdc26",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/590f00f6ba3ad5b133c7b23091355d35951be5b2",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/ff16b965893c96d667dbf8ba1311d5fc734dacf3",
            width: 64
          }
        ],
        name: "Sabotage (LIVE Acoustic)",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 2,
        type: "album",
        uri: "spotify:album:48ZwTu08oO1in9tgSh6aGY"
      },
      {
        album_type: "album",
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0wnsM0ziqToBwQeEbH0akL"
            },
            href: "https://api.spotify.com/v1/artists/0wnsM0ziqToBwQeEbH0akL",
            id: "0wnsM0ziqToBwQeEbH0akL",
            name: "Social Club Misfits",
            type: "artist",
            uri: "spotify:artist:0wnsM0ziqToBwQeEbH0akL"
          }
        ],
        available_markets: [
          "AE",
          "AU",
          "BG",
          "BH",
          "CY",
          "EE",
          "EG",
          "FI",
          "GR",
          "HK",
          "ID",
          "IL",
          "IN",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LV",
          "MY",
          "NZ",
          "OM",
          "PH",
          "PS",
          "QA",
          "RO",
          "SA",
          "SG",
          "TH",
          "TR",
          "TW",
          "VN",
          "ZA",
          "AD",
          "AT",
          "BE",
          "CH",
          "CZ",
          "DE",
          "DK",
          "DZ",
          "ES",
          "FR",
          "HU",
          "IT",
          "LI",
          "LU",
          "MA",
          "MC",
          "MT",
          "NL",
          "NO",
          "PL",
          "SE",
          "SK",
          "TN",
          "GB",
          "IE",
          "IS",
          "PT",
          "AR",
          "BR",
          "CL",
          "PY",
          "UY",
          "BO",
          "DO",
          "CA",
          "CO",
          "EC",
          "PA",
          "PE",
          "US",
          "CR",
          "GT",
          "HN",
          "MX",
          "NI",
          "SV"
        ],
        external_urls: {
          spotify: "https://open.spotify.com/album/1N2JItp5ES3Aaeuues0Qar"
        },
        href: "https://api.spotify.com/v1/albums/1N2JItp5ES3Aaeuues0Qar",
        id: "1N2JItp5ES3Aaeuues0Qar",
        images: [
          {
            height: 640,
            url:
              "https://i.scdn.co/image/b792be312e93f21ca725299a30675cedbed7acdf",
            width: 640
          },
          {
            height: 300,
            url:
              "https://i.scdn.co/image/9e38b8f4b0178bdc08fda1cec2646a4733b5037e",
            width: 300
          },
          {
            height: 64,
            url:
              "https://i.scdn.co/image/74e0e7853d495410692a543271b1ce2a4f5707ee",
            width: 64
          }
        ],
        name: "MOOD // DOOM",
        release_date: "2019-12-20",
        release_date_precision: "day",
        total_tracks: 13,
        type: "album",
        uri: "spotify:album:1N2JItp5ES3Aaeuues0Qar"
      }
    ],
    limit: 20,
    next: "https://api.spotify.com/v1/browse/new-releases?offset=20&limit=20",
    offset: 0,
    previous: null,
    total: 100
  }
};
