export const mockedTracksData = {
  href:
    "https://api.spotify.com/v1/playlists/72QT8nJO5nvnlrc7uyYRvv/tracks?offset=0&limit=100",
  items: [
    {
      added_at: "2015-10-26T11:51:04Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/1dpnxi6xgoB2kaRYnnoatZ"
              },
              href: "https://api.spotify.com/v1/artists/1dpnxi6xgoB2kaRYnnoatZ",
              id: "1dpnxi6xgoB2kaRYnnoatZ",
              name: "Miguel Rios",
              type: "artist",
              uri: "spotify:artist:1dpnxi6xgoB2kaRYnnoatZ"
            }
          ],
          available_markets: [
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "JO",
            "JP",
            "KW",
            "LB",
            "LT",
            "LU",
            "LV",
            "MA",
            "MT",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TN",
            "TR",
            "TW",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/1HITxEQK7ac082gDH7ynDR"
          },
          href: "https://api.spotify.com/v1/albums/1HITxEQK7ac082gDH7ynDR",
          id: "1HITxEQK7ac082gDH7ynDR",
          images: [
            {
              height: 635,
              url:
                "https://i.scdn.co/image/d5ad3868600abcf12202a7874d9da86e99660005",
              width: 640
            },
            {
              height: 297,
              url:
                "https://i.scdn.co/image/2a9cf6c1a7ac70bf516fab567c1e17a47f0b802a",
              width: 300
            },
            {
              height: 63,
              url:
                "https://i.scdn.co/image/dd92a10bac2a6c01dfb59d3d578b3c66f6eccf07",
              width: 64
            }
          ],
          name: "Canciones De Amor Para Tiempos Dificiles",
          release_date: "1995-01-01",
          release_date_precision: "day",
          total_tracks: 15,
          type: "album",
          uri: "spotify:album:1HITxEQK7ac082gDH7ynDR"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/1dpnxi6xgoB2kaRYnnoatZ"
            },
            href: "https://api.spotify.com/v1/artists/1dpnxi6xgoB2kaRYnnoatZ",
            id: "1dpnxi6xgoB2kaRYnnoatZ",
            name: "Miguel Rios",
            type: "artist",
            uri: "spotify:artist:1dpnxi6xgoB2kaRYnnoatZ"
          }
        ],
        available_markets: [
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "JO",
          "JP",
          "KW",
          "LB",
          "LT",
          "LU",
          "LV",
          "MA",
          "MT",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TN",
          "TR",
          "TW",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 225800,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "ES6009700180"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/4rOf6mtF2MpDwWipaila0L"
        },
        href: "https://api.spotify.com/v1/tracks/4rOf6mtF2MpDwWipaila0L",
        id: "4rOf6mtF2MpDwWipaila0L",
        is_local: false,
        name: "Santa Lucia",
        popularity: 59,
        preview_url: null,
        track: true,
        track_number: 1,
        type: "track",
        uri: "spotify:track:4rOf6mtF2MpDwWipaila0L"
      },
      video_thumbnail: {
        url: null
      }
    },
    {
      added_at: "2015-10-26T11:51:26Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/0Y8KmFkKOgJybpVobn1onU"
              },
              href: "https://api.spotify.com/v1/artists/0Y8KmFkKOgJybpVobn1onU",
              id: "0Y8KmFkKOgJybpVobn1onU",
              name: "Luciano Pavarotti",
              type: "artist",
              uri: "spotify:artist:0Y8KmFkKOgJybpVobn1onU"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/0vAPLCrkBoPIMbhFuR6KuZ"
          },
          href: "https://api.spotify.com/v1/albums/0vAPLCrkBoPIMbhFuR6KuZ",
          id: "0vAPLCrkBoPIMbhFuR6KuZ",
          images: [
            {
              height: 640,
              url:
                "https://i.scdn.co/image/ab67616d0000b27387c22581491fb8fd249885e4",
              width: 640
            },
            {
              height: 300,
              url:
                "https://i.scdn.co/image/ab67616d00001e0287c22581491fb8fd249885e4",
              width: 300
            },
            {
              height: 64,
              url:
                "https://i.scdn.co/image/ab67616d0000485187c22581491fb8fd249885e4",
              width: 64
            }
          ],
          name: "The 50 Greatest Vocal Hits",
          release_date: "2015-08-31",
          release_date_precision: "day",
          total_tracks: 50,
          type: "album",
          uri: "spotify:album:0vAPLCrkBoPIMbhFuR6KuZ"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4vHK0wAa73KIgQzxeowBbh"
            },
            href: "https://api.spotify.com/v1/artists/4vHK0wAa73KIgQzxeowBbh",
            id: "4vHK0wAa73KIgQzxeowBbh",
            name: "Alfredo Mazzucchi",
            type: "artist",
            uri: "spotify:artist:4vHK0wAa73KIgQzxeowBbh"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2q0Rkp6Ud5XxPTCkCCdbYr"
            },
            href: "https://api.spotify.com/v1/artists/2q0Rkp6Ud5XxPTCkCCdbYr",
            id: "2q0Rkp6Ud5XxPTCkCCdbYr",
            name: "Eduardo di Capua",
            type: "artist",
            uri: "spotify:artist:2q0Rkp6Ud5XxPTCkCCdbYr"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/68GjvtnJaBEP7b6Qd8JDRg"
            },
            href: "https://api.spotify.com/v1/artists/68GjvtnJaBEP7b6Qd8JDRg",
            id: "68GjvtnJaBEP7b6Qd8JDRg",
            name: "Giancarlo Chiaramello",
            type: "artist",
            uri: "spotify:artist:68GjvtnJaBEP7b6Qd8JDRg"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0Y8KmFkKOgJybpVobn1onU"
            },
            href: "https://api.spotify.com/v1/artists/0Y8KmFkKOgJybpVobn1onU",
            id: "0Y8KmFkKOgJybpVobn1onU",
            name: "Luciano Pavarotti",
            type: "artist",
            uri: "spotify:artist:0Y8KmFkKOgJybpVobn1onU"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/2Ek1WGW7WeyDoxsZiu0AAd"
            },
            href: "https://api.spotify.com/v1/artists/2Ek1WGW7WeyDoxsZiu0AAd",
            id: "2Ek1WGW7WeyDoxsZiu0AAd",
            name: "National Philharmonic Orchestra",
            type: "artist",
            uri: "spotify:artist:2Ek1WGW7WeyDoxsZiu0AAd"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 206586,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "GBF077900300"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/5Z0x77JmLkFaZOmXlaOzs8"
        },
        href: "https://api.spotify.com/v1/tracks/5Z0x77JmLkFaZOmXlaOzs8",
        id: "5Z0x77JmLkFaZOmXlaOzs8",
        is_local: false,
        name: "'O sole mio",
        popularity: 36,
        preview_url: null,
        track: true,
        track_number: 2,
        type: "track",
        uri: "spotify:track:5Z0x77JmLkFaZOmXlaOzs8"
      },
      video_thumbnail: {
        url: null
      }
    },
    {
      added_at: "2015-10-26T11:51:43Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/5Z1XZyEFY0dewG8faEIiEx"
              },
              href: "https://api.spotify.com/v1/artists/5Z1XZyEFY0dewG8faEIiEx",
              id: "5Z1XZyEFY0dewG8faEIiEx",
              name: "Django Reinhardt",
              type: "artist",
              uri: "spotify:artist:5Z1XZyEFY0dewG8faEIiEx"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/7IPOIivgoNxoXefPUQpIgh"
          },
          href: "https://api.spotify.com/v1/albums/7IPOIivgoNxoXefPUQpIgh",
          id: "7IPOIivgoNxoXefPUQpIgh",
          images: [
            {
              height: 640,
              url:
                "https://i.scdn.co/image/ab67616d0000b273c237a9baf06c29e5d0b50a2b",
              width: 640
            },
            {
              height: 300,
              url:
                "https://i.scdn.co/image/ab67616d00001e02c237a9baf06c29e5d0b50a2b",
              width: 300
            },
            {
              height: 64,
              url:
                "https://i.scdn.co/image/ab67616d00004851c237a9baf06c29e5d0b50a2b",
              width: 64
            }
          ],
          name: "United States Harmonious Wail: Gypsy Swing",
          release_date: "2003-09-01",
          release_date_precision: "day",
          total_tracks: 18,
          type: "album",
          uri: "spotify:album:7IPOIivgoNxoXefPUQpIgh"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0oiYyKo8F9Bm80L02whvQ1"
            },
            href: "https://api.spotify.com/v1/artists/0oiYyKo8F9Bm80L02whvQ1",
            id: "0oiYyKo8F9Bm80L02whvQ1",
            name: "Harmonious Wail",
            type: "artist",
            uri: "spotify:artist:0oiYyKo8F9Bm80L02whvQ1"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5hQOzacYqR75REze0urPGZ"
            },
            href: "https://api.spotify.com/v1/artists/5hQOzacYqR75REze0urPGZ",
            id: "5hQOzacYqR75REze0urPGZ",
            name: "Vasily Pavlovich Solov'yov-Sedoy",
            type: "artist",
            uri: "spotify:artist:5hQOzacYqR75REze0urPGZ"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/7aZV27zKF02pwuWdKs7ySH"
            },
            href: "https://api.spotify.com/v1/artists/7aZV27zKF02pwuWdKs7ySH",
            id: "7aZV27zKF02pwuWdKs7ySH",
            name: "Sims Delaney-Potthoff",
            type: "artist",
            uri: "spotify:artist:7aZV27zKF02pwuWdKs7ySH"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 220760,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "HKI190324901"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/0R4IeYxxn5d58VoU6BeyXF"
        },
        href: "https://api.spotify.com/v1/tracks/0R4IeYxxn5d58VoU6BeyXF",
        id: "0R4IeYxxn5d58VoU6BeyXF",
        is_local: false,
        name: "Moscow Nights",
        popularity: 18,
        preview_url:
          "https://p.scdn.co/mp3-preview/e3e9be4b08dd4cf1e3e9b08fdd65a72ed7a1a943?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track: true,
        track_number: 1,
        type: "track",
        uri: "spotify:track:0R4IeYxxn5d58VoU6BeyXF"
      },
      video_thumbnail: {
        url: null
      }
    },
    {
      added_at: "2015-10-26T11:53:34Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/4yNluGAiPbYXLwlA9KspbG"
              },
              href: "https://api.spotify.com/v1/artists/4yNluGAiPbYXLwlA9KspbG",
              id: "4yNluGAiPbYXLwlA9KspbG",
              name: "The Red Army Choir",
              type: "artist",
              uri: "spotify:artist:4yNluGAiPbYXLwlA9KspbG"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/3pzeurUsHJK1ueinchI4MB"
          },
          href: "https://api.spotify.com/v1/albums/3pzeurUsHJK1ueinchI4MB",
          id: "3pzeurUsHJK1ueinchI4MB",
          images: [
            {
              height: 640,
              url:
                "https://i.scdn.co/image/ab67616d0000b27396e5df15eb94600f301d6fea",
              width: 640
            },
            {
              height: 300,
              url:
                "https://i.scdn.co/image/ab67616d00001e0296e5df15eb94600f301d6fea",
              width: 300
            },
            {
              height: 64,
              url:
                "https://i.scdn.co/image/ab67616d0000485196e5df15eb94600f301d6fea",
              width: 64
            }
          ],
          name: "The Red Army Choir",
          release_date: "2008-02-25",
          release_date_precision: "day",
          total_tracks: 36,
          type: "album",
          uri: "spotify:album:3pzeurUsHJK1ueinchI4MB"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/4yNluGAiPbYXLwlA9KspbG"
            },
            href: "https://api.spotify.com/v1/artists/4yNluGAiPbYXLwlA9KspbG",
            id: "4yNluGAiPbYXLwlA9KspbG",
            name: "The Red Army Choir",
            type: "artist",
            uri: "spotify:artist:4yNluGAiPbYXLwlA9KspbG"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 270346,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "FRX080090345"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/38wicLanOGFVTKtkKcSMnn"
        },
        href: "https://api.spotify.com/v1/tracks/38wicLanOGFVTKtkKcSMnn",
        id: "38wicLanOGFVTKtkKcSMnn",
        is_local: false,
        name: "Kalinka",
        popularity: 39,
        preview_url:
          "https://p.scdn.co/mp3-preview/530345dcb21c042be5a276a631aad8c70adb3cf2?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track: true,
        track_number: 10,
        type: "track",
        uri: "spotify:track:38wicLanOGFVTKtkKcSMnn"
      },
      video_thumbnail: {
        url: null
      }
    },
    {
      added_at: "2015-10-26T11:53:39Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/3hJv5p2HwekJysNB2NDnEC"
              },
              href: "https://api.spotify.com/v1/artists/3hJv5p2HwekJysNB2NDnEC",
              id: "3hJv5p2HwekJysNB2NDnEC",
              name: "André Rieu",
              type: "artist",
              uri: "spotify:artist:3hJv5p2HwekJysNB2NDnEC"
            }
          ],
          available_markets: [],
          external_urls: {
            spotify: "https://open.spotify.com/album/4Pq9L9Jr2S7O5u8cbHm9po"
          },
          href: "https://api.spotify.com/v1/albums/4Pq9L9Jr2S7O5u8cbHm9po",
          id: "4Pq9L9Jr2S7O5u8cbHm9po",
          images: [
            {
              height: 640,
              url:
                "https://i.scdn.co/image/ab67616d0000b273646e4ebf5cdd9572e92b0741",
              width: 640
            },
            {
              height: 300,
              url:
                "https://i.scdn.co/image/ab67616d00001e02646e4ebf5cdd9572e92b0741",
              width: 300
            },
            {
              height: 64,
              url:
                "https://i.scdn.co/image/ab67616d00004851646e4ebf5cdd9572e92b0741",
              width: 64
            }
          ],
          name: "La Vie Est Belle",
          release_date: "2000-01-01",
          release_date_precision: "day",
          total_tracks: 17,
          type: "album",
          uri: "spotify:album:4Pq9L9Jr2S7O5u8cbHm9po"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/3hJv5p2HwekJysNB2NDnEC"
            },
            href: "https://api.spotify.com/v1/artists/3hJv5p2HwekJysNB2NDnEC",
            id: "3hJv5p2HwekJysNB2NDnEC",
            name: "André Rieu",
            type: "artist",
            uri: "spotify:artist:3hJv5p2HwekJysNB2NDnEC"
          },
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/51HxUAjeZIOv4aniusaDkT"
            },
            href: "https://api.spotify.com/v1/artists/51HxUAjeZIOv4aniusaDkT",
            id: "51HxUAjeZIOv4aniusaDkT",
            name: "Johann Strauss Orchestra",
            type: "artist",
            uri: "spotify:artist:51HxUAjeZIOv4aniusaDkT"
          }
        ],
        available_markets: [],
        disc_number: 1,
        duration_ms: 143293,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "DEN120002312"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/5Cdz4eQjBgLIt2cRXXdTMR"
        },
        href: "https://api.spotify.com/v1/tracks/5Cdz4eQjBgLIt2cRXXdTMR",
        id: "5Cdz4eQjBgLIt2cRXXdTMR",
        is_local: false,
        name: "Kalinka",
        popularity: 0,
        preview_url: null,
        track: true,
        track_number: 6,
        type: "track",
        uri: "spotify:track:5Cdz4eQjBgLIt2cRXXdTMR"
      },
      video_thumbnail: {
        url: null
      }
    },
    {
      added_at: "2015-10-26T11:54:00Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "compilation",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
              },
              href: "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
              id: "0LyfQWJT6nXafLPZqxe9Of",
              name: "Çeşitli Sanatçılar",
              type: "artist",
              uri: "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/4QXXjx1e5pnwaHNLHmmhdp"
          },
          href: "https://api.spotify.com/v1/albums/4QXXjx1e5pnwaHNLHmmhdp",
          id: "4QXXjx1e5pnwaHNLHmmhdp",
          images: [
            {
              height: 640,
              url:
                "https://i.scdn.co/image/ab67616d0000b273fdb77b6e71dd8e9b6a12354f",
              width: 640
            },
            {
              height: 300,
              url:
                "https://i.scdn.co/image/ab67616d00001e02fdb77b6e71dd8e9b6a12354f",
              width: 300
            },
            {
              height: 64,
              url:
                "https://i.scdn.co/image/ab67616d00004851fdb77b6e71dd8e9b6a12354f",
              width: 64
            }
          ],
          name: "Altın Şarkılar 9",
          release_date: "1995-02-13",
          release_date_precision: "day",
          total_tracks: 12,
          type: "album",
          uri: "spotify:album:4QXXjx1e5pnwaHNLHmmhdp"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/28qT1U6wHdW2WSCGdA7ZDQ"
            },
            href: "https://api.spotify.com/v1/artists/28qT1U6wHdW2WSCGdA7ZDQ",
            id: "28qT1U6wHdW2WSCGdA7ZDQ",
            name: "Zekai Tunca",
            type: "artist",
            uri: "spotify:artist:28qT1U6wHdW2WSCGdA7ZDQ"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 197044,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "TR0040500108"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/3On5AHfgDkpMrjLF0QSi70"
        },
        href: "https://api.spotify.com/v1/tracks/3On5AHfgDkpMrjLF0QSi70",
        id: "3On5AHfgDkpMrjLF0QSi70",
        is_local: false,
        name: "Eski Dostlar",
        popularity: 24,
        preview_url:
          "https://p.scdn.co/mp3-preview/dc321bb759ece84991eaefdb875ba2a71ed83df7?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track: true,
        track_number: 12,
        type: "track",
        uri: "spotify:track:3On5AHfgDkpMrjLF0QSi70"
      },
      video_thumbnail: {
        url: null
      }
    },
    {
      added_at: "2015-10-26T11:54:26Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/43ZHCT0cAZBISjO8DG9PnE"
              },
              href: "https://api.spotify.com/v1/artists/43ZHCT0cAZBISjO8DG9PnE",
              id: "43ZHCT0cAZBISjO8DG9PnE",
              name: "Elvis Presley",
              type: "artist",
              uri: "spotify:artist:43ZHCT0cAZBISjO8DG9PnE"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/5Iec810oL6PorbyBVjLnmD"
          },
          href: "https://api.spotify.com/v1/albums/5Iec810oL6PorbyBVjLnmD",
          id: "5Iec810oL6PorbyBVjLnmD",
          images: [
            {
              height: 640,
              url:
                "https://i.scdn.co/image/ab67616d0000b273a22455d1ff7031adeaa90a40",
              width: 640
            },
            {
              height: 300,
              url:
                "https://i.scdn.co/image/ab67616d00001e02a22455d1ff7031adeaa90a40",
              width: 300
            },
            {
              height: 64,
              url:
                "https://i.scdn.co/image/ab67616d00004851a22455d1ff7031adeaa90a40",
              width: 64
            }
          ],
          name: "Elvis' Golden Records, Vol. 3",
          release_date: "1963-08-11",
          release_date_precision: "day",
          total_tracks: 12,
          type: "album",
          uri: "spotify:album:5Iec810oL6PorbyBVjLnmD"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/43ZHCT0cAZBISjO8DG9PnE"
            },
            href: "https://api.spotify.com/v1/artists/43ZHCT0cAZBISjO8DG9PnE",
            id: "43ZHCT0cAZBISjO8DG9PnE",
            name: "Elvis Presley",
            type: "artist",
            uri: "spotify:artist:43ZHCT0cAZBISjO8DG9PnE"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 195906,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "USRC10200339"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/5mlaaeSzFsH4ouhLrUHCbw"
        },
        href: "https://api.spotify.com/v1/tracks/5mlaaeSzFsH4ouhLrUHCbw",
        id: "5mlaaeSzFsH4ouhLrUHCbw",
        is_local: false,
        name: "It's Now or Never",
        popularity: 57,
        preview_url:
          "https://p.scdn.co/mp3-preview/0c7df8959de670ab3aafeadae399416956be059e?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track: true,
        track_number: 1,
        type: "track",
        uri: "spotify:track:5mlaaeSzFsH4ouhLrUHCbw"
      },
      video_thumbnail: {
        url: null
      }
    },
    {
      added_at: "2015-10-26T11:55:17Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/5e09ho29ZPeMNUtwzkMdn8"
              },
              href: "https://api.spotify.com/v1/artists/5e09ho29ZPeMNUtwzkMdn8",
              id: "5e09ho29ZPeMNUtwzkMdn8",
              name: "İstanbul Klasik Türk Müziği Korosu",
              type: "artist",
              uri: "spotify:artist:5e09ho29ZPeMNUtwzkMdn8"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/1fxn8xZ5FT8N8Fk3Db7p98"
          },
          href: "https://api.spotify.com/v1/albums/1fxn8xZ5FT8N8Fk3Db7p98",
          id: "1fxn8xZ5FT8N8Fk3Db7p98",
          images: [
            {
              height: 640,
              url:
                "https://i.scdn.co/image/ab67616d0000b273c3e2f0498a471f057cf9d2ee",
              width: 640
            },
            {
              height: 300,
              url:
                "https://i.scdn.co/image/ab67616d00001e02c3e2f0498a471f057cf9d2ee",
              width: 300
            },
            {
              height: 64,
              url:
                "https://i.scdn.co/image/ab67616d00004851c3e2f0498a471f057cf9d2ee",
              width: 64
            }
          ],
          name: "Dede Efendi Fasıllar",
          release_date: "2012-04-28",
          release_date_precision: "day",
          total_tracks: 16,
          type: "album",
          uri: "spotify:album:1fxn8xZ5FT8N8Fk3Db7p98"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/5e09ho29ZPeMNUtwzkMdn8"
            },
            href: "https://api.spotify.com/v1/artists/5e09ho29ZPeMNUtwzkMdn8",
            id: "5e09ho29ZPeMNUtwzkMdn8",
            name: "İstanbul Klasik Türk Müziği Korosu",
            type: "artist",
            uri: "spotify:artist:5e09ho29ZPeMNUtwzkMdn8"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 191706,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "TR0380602427"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/79w72V5QT5Ovfid33nQcAE"
        },
        href: "https://api.spotify.com/v1/tracks/79w72V5QT5Ovfid33nQcAE",
        id: "79w72V5QT5Ovfid33nQcAE",
        is_local: false,
        name: "Yine Bir Gül Nihâl",
        popularity: 23,
        preview_url:
          "https://p.scdn.co/mp3-preview/13d4f3b857a68a4c8db800cab58679235cf9ddfb?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track: true,
        track_number: 7,
        type: "track",
        uri: "spotify:track:79w72V5QT5Ovfid33nQcAE"
      },
      video_thumbnail: {
        url: null
      }
    },
    {
      added_at: "2015-10-26T11:55:42Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/0K9pSmFx0kWESA9jqx8aCW"
              },
              href: "https://api.spotify.com/v1/artists/0K9pSmFx0kWESA9jqx8aCW",
              id: "0K9pSmFx0kWESA9jqx8aCW",
              name: "Gaby Moreno",
              type: "artist",
              uri: "spotify:artist:0K9pSmFx0kWESA9jqx8aCW"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/7HRTTbRSiCmqcUYeiJtPnJ"
          },
          href: "https://api.spotify.com/v1/albums/7HRTTbRSiCmqcUYeiJtPnJ",
          id: "7HRTTbRSiCmqcUYeiJtPnJ",
          images: [
            {
              height: 640,
              url:
                "https://i.scdn.co/image/ab67616d0000b273ba8f760412380f0a5e8e42a1",
              width: 640
            },
            {
              height: 300,
              url:
                "https://i.scdn.co/image/ab67616d00001e02ba8f760412380f0a5e8e42a1",
              width: 300
            },
            {
              height: 64,
              url:
                "https://i.scdn.co/image/ab67616d00004851ba8f760412380f0a5e8e42a1",
              width: 64
            }
          ],
          name: "Still The Unkown",
          release_date: "2008-06-24",
          release_date_precision: "day",
          total_tracks: 10,
          type: "album",
          uri: "spotify:album:7HRTTbRSiCmqcUYeiJtPnJ"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/0K9pSmFx0kWESA9jqx8aCW"
            },
            href: "https://api.spotify.com/v1/artists/0K9pSmFx0kWESA9jqx8aCW",
            id: "0K9pSmFx0kWESA9jqx8aCW",
            name: "Gaby Moreno",
            type: "artist",
            uri: "spotify:artist:0K9pSmFx0kWESA9jqx8aCW"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 217613,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "ushm20830751"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/1JW1QpeuA7UAjtzSQxzgxk"
        },
        href: "https://api.spotify.com/v1/tracks/1JW1QpeuA7UAjtzSQxzgxk",
        id: "1JW1QpeuA7UAjtzSQxzgxk",
        is_local: false,
        name: "Amapola",
        popularity: 40,
        preview_url:
          "https://p.scdn.co/mp3-preview/8e6956489213322b3f8ccb21c8352614942202ba?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track: true,
        track_number: 6,
        type: "track",
        uri: "spotify:track:1JW1QpeuA7UAjtzSQxzgxk"
      },
      video_thumbnail: {
        url: null
      }
    },
    {
      added_at: "2015-10-26T11:56:28Z",
      added_by: {
        external_urls: {
          spotify: "https://open.spotify.com/user/test"
        },
        href: "https://api.spotify.com/v1/users/test",
        id: "test",
        type: "user",
        uri: "spotify:user:test"
      },
      is_local: false,
      primary_color: null,
      track: {
        album: {
          album_type: "album",
          artists: [
            {
              external_urls: {
                spotify:
                  "https://open.spotify.com/artist/03a5eVjzFyQlR4XyVSwt4t"
              },
              href: "https://api.spotify.com/v1/artists/03a5eVjzFyQlR4XyVSwt4t",
              id: "03a5eVjzFyQlR4XyVSwt4t",
              name: "Love and Theft",
              type: "artist",
              uri: "spotify:artist:03a5eVjzFyQlR4XyVSwt4t"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          external_urls: {
            spotify: "https://open.spotify.com/album/6mdbwD2OEFexB0lPXoRofQ"
          },
          href: "https://api.spotify.com/v1/albums/6mdbwD2OEFexB0lPXoRofQ",
          id: "6mdbwD2OEFexB0lPXoRofQ",
          images: [
            {
              height: 640,
              url:
                "https://i.scdn.co/image/2bb40dd032520c90de4be79ee5c11783255f5c11",
              width: 640
            },
            {
              height: 300,
              url:
                "https://i.scdn.co/image/02a0c7fccb51ff5821b798b66ce390ef403950b2",
              width: 300
            },
            {
              height: 64,
              url:
                "https://i.scdn.co/image/4b3b71f1462498201872983b75117be1df74cbf9",
              width: 64
            }
          ],
          name: "Love and Theft",
          release_date: "2012-07-24",
          release_date_precision: "day",
          total_tracks: 11,
          type: "album",
          uri: "spotify:album:6mdbwD2OEFexB0lPXoRofQ"
        },
        artists: [
          {
            external_urls: {
              spotify: "https://open.spotify.com/artist/03a5eVjzFyQlR4XyVSwt4t"
            },
            href: "https://api.spotify.com/v1/artists/03a5eVjzFyQlR4XyVSwt4t",
            id: "03a5eVjzFyQlR4XyVSwt4t",
            name: "Love and Theft",
            type: "artist",
            uri: "spotify:artist:03a5eVjzFyQlR4XyVSwt4t"
          }
        ],
        available_markets: [
          "AD",
          "AE",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BH",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IS",
          "IT",
          "JO",
          "JP",
          "KW",
          "LB",
          "LI",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PH",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "SA",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TN",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        disc_number: 1,
        duration_ms: 186626,
        episode: false,
        explicit: false,
        external_ids: {
          isrc: "USRN11100128"
        },
        external_urls: {
          spotify: "https://open.spotify.com/track/63w0QA1wiV7QhF9jeiHETF"
        },
        href: "https://api.spotify.com/v1/tracks/63w0QA1wiV7QhF9jeiHETF",
        id: "63w0QA1wiV7QhF9jeiHETF",
        is_local: false,
        name: "Angel Eyes",
        popularity: 62,
        preview_url:
          "https://p.scdn.co/mp3-preview/f59247041d5822764d4e401bded30c73e7c68e30?cid=5bcff691b8a04bac809e087d8a0ce7f9",
        track: true,
        track_number: 1,
        type: "track",
        uri: "spotify:track:63w0QA1wiV7QhF9jeiHETF"
      },
      video_thumbnail: {
        url: null
      }
    }
  ],
  limit: 100,
  next: null,
  offset: 0,
  previous: null,
  total: 10
};
